M48
; DRILL file {KiCad 8.0.1-8.0.1-1~ubuntu22.04.1} date 2024-10-18T14:30:21+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-10-18T14:30:21+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1-8.0.1-1~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C4.000
%
G90
G05
T1
X77.66Y-33.18
X77.66Y-44.98
T2
X62.0Y-105.0
X62.0Y-171.0
X128.0Y-105.0
X128.0Y-171.0
T3
X64.2Y-26.85
T4
X57.5Y-100.5
X57.5Y-175.5
X132.5Y-100.5
X132.5Y-175.5
M30
